### ISSUE TITLE
Consider using `var` keyword for variable declaration.

### ISSUE THREAD

**Issue by jmalloc** [oxidelang/oxide#1]
I originally wanted to avoid the need for a keyword here, but adding it will allow for more concise syntax when dealing with variants.

* `x : any` becomes `var x` 
* `x : someType` becomes `var x : someType`
* `x : any = 0` becomes `var x = 0`

Function parameter lists do not need to use the keyword, hence the following are valid:

* `(x) {}` was `(x : any) {}`
* `(x : someType) {}`
* `(x = 0) {}` was `(x : any = 0) {}`
* `(x : someType = 0) {}` was `(x : someType = 0) {}`

**Comment by jmalloc** [comment]
@koden-km, what do you think about a `var` keyword being used to declare new variables?

**Comment by koden-km** [comment]
The `var` keyword seems fine to me. I used them in Go and Swift and it seemed good.
Swift's `let` keyword/feature for making immutable vars was pretty win though.

**Comment by jmalloc** [comment]
What is it you like about having const local vars?

**Comment by jmalloc** [comment]
Ok, after our discussion let's roll with this:

```
name : type;         // declare variable named "name" of type "type"
name : type = value; // declare variable named "name" of type "type" with value "value"
name : = value;      // declare variable named "name" of type typeof(value) with value "value"
```
The syntax is identical inside a function parameter list.  The type name can only be omitted if the type of value is known at compile time.
